### ISSUE TITLE
Comment-sectie

### ISSUE THREAD

**Issue by IvarSchuyt** [kosterm14/the-web-is-for-everyone-interactive-functionality#1]
Als ik jou was zou ik een header geven aan de sectie waarin comments ingeladen zijn, om de pagina iets duidelijker te maken.

**Comment by kosterm14** [comment]
![image](https://user-images.githubusercontent.com/61830362/229298699-10929472-7a84-4db8-8f1c-ee458d49fe06.png)

Comment sections hebben een header nu tyyy (negeer de haatcomment)
