### ISSUE TITLE
navbar aanpassen

### ISSUE THREAD

**Issue by Trisjan** [kosterm14/the-web-is-for-everyone-interactive-functionality#3]
![image](https://user-images.githubusercontent.com/74552944/229065579-5d594acd-e22a-4043-a152-335daabfc440.png)

Bij de navbar staat een terug naar overzicht knop maar ook als je al bij de overzichtspagina bent

**Comment by kosterm14** [comment]
Goed gezien, ik zal het weghalen tyy
