### ISSUE TITLE
Meer consistent in de kaartjes en hun groottes

### ISSUE THREAD

**Issue by Trisjan** [kosterm14/the-web-is-for-everyone-interactive-functionality#4]
![image](https://user-images.githubusercontent.com/74552944/229066041-f9aca219-bb1d-490d-af58-02299b484895.png)

Maak alle kaartjes gelijk in de groottes

**Comment by kosterm14** [comment]
Alle kaartjes zijn nu precies even groot tyy

**Comment by kosterm14** [comment]
Mooie screenshot trouwens met dat rood
