### ISSUE TITLE
Placeholder image

### ISSUE THREAD

**Issue by moonlightlizaa** [kosterm14/the-web-is-for-everyone-interactive-functionality#6]
<img width="263" alt="Screenshot 2023-03-31 at 10 39 22 AM" src="https://user-images.githubusercontent.com/106411511/229070575-fe9bb1b1-0bba-4eca-8836-d09e446cd536.png">

Misschien leuker als je een andere placeholder image gebruikt, dat meer past bij de huisstijl van de opdrachtgever. 

Voorbeeld: 

<img width="402" alt="Screenshot 2023-03-31 at 10 40 31 AM" src="https://user-images.githubusercontent.com/106411511/229070870-3fbcff01-9752-4206-bca1-a83ad86feaa5.png">

**Comment by kosterm14** [comment]
okeeeeee zal ik doen
